dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  nameserver:
  - 192.168.124.10
  fake-ip-filter:
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
tun:
  enable: true
  stake: system
  dns-hijack:
  - udp://any:53
  auto-route: true
  auto-detect-interface: true

sub:
  - https://moes.lnaspiring.com/Moe233-Subs/aln/api/v1/client/subscribe?token=857c49b06b064690eca348e827a80dbd
